
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GerenciaVIEW;

import GerenciaDAO.Update_tarefasDAO;
import GerenciaDTO.tarefasDTO;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;

/**
 *
 * @author Aluno
 */
public class Editar extends javax.swing.JFrame {

    /**
     * Creates new form MeuProjeto
     */
    public Editar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnrBaixa = new javax.swing.JRadioButton();
        btnrMedia = new javax.swing.JRadioButton();
        btnrAlta = new javax.swing.JRadioButton();
        btnOK_Editar = new javax.swing.JButton();
        cbTarefaClocluida = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_Inicio = new javax.swing.JMenu();
        menu_Minhas_Tarefas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar Tarefa"));

        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });

        jLabel1.setText("Título da tarefa");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setText("(opcional)");

        jLabel2.setText("Descrição ");

        jLabel6.setText("Código da tarefa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(txtDescricao)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Prioridade"));

        btnrBaixa.setText("Baixa");
        btnrBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrBaixaActionPerformed(evt);
            }
        });

        btnrMedia.setText("Média");

        btnrAlta.setText("Alta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnrBaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnrMedia)
                .addGap(65, 65, 65)
                .addComponent(btnrAlta)
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnrBaixa)
                    .addComponent(btnrMedia)
                    .addComponent(btnrAlta))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnOK_Editar.setText("OK");
        btnOK_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK_EditarActionPerformed(evt);
            }
        });

        cbTarefaClocluida.setText("Tarefa concluída");

        menu_Inicio.setText("Nova tarefa");
        menu_Inicio.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menu_InicioMenuSelected(evt);
            }
        });
        jMenuBar1.add(menu_Inicio);

        menu_Minhas_Tarefas.setText("Minhas tarefas");
        menu_Minhas_Tarefas.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menu_Minhas_TarefasMenuSelected(evt);
            }
        });
        jMenuBar1.add(menu_Minhas_Tarefas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(cbTarefaClocluida)
                        .addGap(39, 39, 39)
                        .addComponent(btnOK_Editar)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK_Editar)
                    .addComponent(cbTarefaClocluida))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    private void btnrBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrBaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrBaixaActionPerformed

    private void btnOK_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK_EditarActionPerformed
        tarefasDTO objtarefasDTO = new tarefasDTO();
        Update_tarefasDAO updateTarefasDAO = new Update_tarefasDAO();
        String codigo = txt_codigo.getText();
        String titulo = txtTitle.getText();
        String descri = txtDescricao.getText();
        String prioridade = getSelectedPriority();

        if (codigo.isEmpty()) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Sem o código da tarefa não haverá mudança");
        } else {
            objtarefasDTO.setCodigo(Integer.parseInt(codigo));
            if (cbTarefaClocluida.isSelected()) {
                objtarefasDTO.setConcluido(true);
            }
            if (!titulo.isEmpty()) {
                objtarefasDTO.setTitle(titulo);
            }
            if (!descri.isEmpty()) {
                objtarefasDTO.setDescri(descri);
            }
            if (prioridade != null) {
                objtarefasDTO.setPrioridade(prioridade);
            }

            updateTarefasDAO.updateTarefa(objtarefasDTO);
            JOptionPane.showMessageDialog(null, "Alteração realizada!");
        }
    }//GEN-LAST:event_btnOK_EditarActionPerformed

    private void menu_Minhas_TarefasMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menu_Minhas_TarefasMenuSelected
       MinhasTarefas minhasTarefas = new MinhasTarefas();
       minhasTarefas.setVisible(true);
       dispose();
    }//GEN-LAST:event_menu_Minhas_TarefasMenuSelected

    private void menu_InicioMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menu_InicioMenuSelected
       NovaTarefa novaTarefa = new NovaTarefa();
       novaTarefa.setVisible(true);
       dispose();
    }//GEN-LAST:event_menu_InicioMenuSelected

    

    private String getSelectedPriority() {
        if (btnrBaixa.isSelected()) {
            return "baixa";
        } else if (btnrMedia.isSelected()) {
            return "média";
        } else if (btnrAlta.isSelected()) {
            return "alta";
        } else {
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Editar().setVisible(true);
            }
        });
    }
    /*
    private void alterar_valores() {
        try {
            get_tarefasDAO objget_tarefasDAO = new get_tarefasDAO();
            DefaultTableModel model = (DefaultTableModel) table_tarefas.getModel();
            model.setNumRows(0);

            ArrayList<tarefasDTO> listaL = objget_tarefasDAO.getTarefasDAO();

            for (int num = 0; num < listaL.size(); num++) {
                model.addRow(new Object[]{
                    listaL.get(num).getCodigo(),
                    listaL.get(num).getTitle(),
                    listaL.get(num).getDescri(),
                    listaL.get(num).getPrazo(),
                    listaL.get(num).getDataInicial(),
                    listaL.get(num).isConcluido(),
                    listaL.get(num).getPrioridade()
                });

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "formlistar :" + e);
        }
    };
    };
    };
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK_Editar;
    private javax.swing.JRadioButton btnrAlta;
    private javax.swing.JRadioButton btnrBaixa;
    private javax.swing.JRadioButton btnrMedia;
    private javax.swing.JCheckBox cbTarefaClocluida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menu_Inicio;
    private javax.swing.JMenu menu_Minhas_Tarefas;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txt_codigo;
    // End of variables declaration//GEN-END:variables

}
