/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GerenciaVIEW;

import GerenciaDAO.InsertBanco_Tarefas;
import GerenciaDTO.tarefasDTO;
import java.awt.Color;

import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

import java.text.ParseException;
import java.text.SimpleDateFormat;

import java.sql.Date;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class NovaTarefa extends javax.swing.JFrame {
    // Inside your NovaTarefa class or wherever you are creating a tarefasDTO object

    /**
     * Creates new form MeuProjeto
     */
    /**
     * Creates new form NovaTarefa
     */
    public NovaTarefa() {

        initComponents();
        txt_Descricao.setCaretColor(Color.BLUE);
        txt_PrazoFinal.setCaretColor(Color.BLUE);
        txt_tituloTarefa.setCaretColor(Color.BLUE);
        // Definir o placeholder para o campo de prazo
        txt_PrazoFinal.setText("yyyy-MM-dd");
        txt_PrazoFinal.setForeground(Color.gray);
        // Adicionar um listener de foco para remover o placeholder quando o campo recebe foco
        txt_PrazoFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txt_PrazoFinal.getText().equals("yyyy-MM-dd")) {
                    txt_PrazoFinal.setText("");
                    txt_PrazoFinal.setForeground(Color.BLACK);
                }
            }
        });

        // Adicionar um listener de foco para adicionar o placeholder se o campo estiver vazio quando perder o foco
        txt_PrazoFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txt_PrazoFinal.getText().isEmpty()) {
                    txt_PrazoFinal.setText("yyyy-MM-dd");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_tituloTarefa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Descricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_PrazoFinal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        radio_Baixa = new javax.swing.JRadioButton();
        radio_media = new javax.swing.JRadioButton();
        radio_alta = new javax.swing.JRadioButton();
        btn_CadastrarTarefa = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_inicio = new javax.swing.JMenu();
        menu_tarefas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nova Tarefa"));

        jLabel4.setText("Prazo Final");

        txt_tituloTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tituloTarefaActionPerformed(evt);
            }
        });

        jLabel1.setText("Título da tarefa");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setText("(opcional)");

        jLabel2.setText("Descrição ");

        txt_PrazoFinal.setName("prazo_teste"); // NOI18N
        txt_PrazoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PrazoFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tituloTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(txt_PrazoFinal)
                    .addComponent(txt_Descricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tituloTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_PrazoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Prioridade"));

        buttonGroup1.add(radio_Baixa);
        radio_Baixa.setText("Baixa");
        radio_Baixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_BaixaActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_media);
        radio_media.setText("Média");

        buttonGroup1.add(radio_alta);
        radio_alta.setText("Alta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(radio_Baixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radio_media)
                .addGap(83, 83, 83)
                .addComponent(radio_alta)
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_Baixa)
                    .addComponent(radio_media)
                    .addComponent(radio_alta))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btn_CadastrarTarefa.setText("Cadastrar tarefa");
        btn_CadastrarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarTarefaActionPerformed(evt);
            }
        });

        menu_inicio.setText("Editar tarefa");
        menu_inicio.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menu_inicioMenuSelected(evt);
            }
        });
        menu_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_inicioActionPerformed(evt);
            }
        });
        jMenuBar1.add(menu_inicio);

        menu_tarefas.setText("Minhas tarefas");
        menu_tarefas.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menu_tarefasMenuSelected(evt);
            }
        });
        menu_tarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tarefasActionPerformed(evt);
            }
        });
        jMenuBar1.add(menu_tarefas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btn_CadastrarTarefa)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_CadastrarTarefa)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tituloTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tituloTarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tituloTarefaActionPerformed

    private void radio_BaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_BaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_BaixaActionPerformed

    private void btn_CadastrarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarTarefaActionPerformed
        String title, descri, prazo, prioridade = "";
        tarefasDTO tarefas = new tarefasDTO();

        // Inicializar utilDataInicial com a data e hora atual
        java.util.Date utilDataInicial = new java.util.Date();
        tarefas.setUtilDataInicial(new Date(utilDataInicial.getTime()));

        try {
            title = txt_tituloTarefa.getText();
            descri = txt_Descricao.getText();
            prazo = txt_PrazoFinal.getText();

            if (title.isEmpty() || prazo.isEmpty() || !isDateValid(prazo) || getSelectedPriority() == null) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Preencha todos os campos exigidos ou selecione uma prioridade válida.");
            } else {
                SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
                Date data = new Date(formato.parse(prazo).getTime());

                tarefas.setDescri(descri);
                tarefas.setPrazo(data);
                tarefas.setTitle(title);
                tarefas.setDataInicial(new Date(utilDataInicial.getTime())); // Definir a data inicial aqui

                prioridade = getSelectedPriority();
                tarefas.setPrioridade(prioridade);

                InsertBanco_Tarefas insert_tarefas = new InsertBanco_Tarefas();
                insert_tarefas.cad_Tarefas(tarefas);
                JOptionPane.showMessageDialog(null, "Tarefa agendada");
                txt_Descricao.setText("");
                txt_PrazoFinal.setText("");
                txt_tituloTarefa.setText("");
                buttonGroup1.clearSelection();
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Erro ao pegar dados: " + e.getMessage());
        }
    }

    private boolean isDateValid(String date) {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        formato.setLenient(false);
        try {
            formato.parse(date);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }

    private String getSelectedPriority() {
        if (radio_Baixa.isSelected()) {
            return "baixa";
        } else if (radio_media.isSelected()) {
            return "média";
        } else if (radio_alta.isSelected()) {
            return "alta";
        } else {
            return null;
        }
    }//GEN-LAST:event_btn_CadastrarTarefaActionPerformed


    private void txt_PrazoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PrazoFinalActionPerformed


    }//GEN-LAST:event_txt_PrazoFinalActionPerformed

    private void menu_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_inicioActionPerformed

    }//GEN-LAST:event_menu_inicioActionPerformed

    private void menu_tarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tarefasActionPerformed

    }//GEN-LAST:event_menu_tarefasActionPerformed

    private void menu_tarefasMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menu_tarefasMenuSelected
        MinhasTarefas view_MYtarefas = new MinhasTarefas();
        view_MYtarefas.setVisible(true);
        dispose();
    }//GEN-LAST:event_menu_tarefasMenuSelected

    private void menu_inicioMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menu_inicioMenuSelected
        Editar objeditar = new Editar();
        objeditar.setVisible(true);
        dispose();
    }//GEN-LAST:event_menu_inicioMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new NovaTarefa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CadastrarTarefa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menu_inicio;
    private javax.swing.JMenu menu_tarefas;
    private javax.swing.JRadioButton radio_Baixa;
    private javax.swing.JRadioButton radio_alta;
    private javax.swing.JRadioButton radio_media;
    private javax.swing.JTextField txt_Descricao;
    private javax.swing.JTextField txt_PrazoFinal;
    private javax.swing.JTextField txt_tituloTarefa;
    // End of variables declaration//GEN-END:variables
}
